### ISSUE TITLE
Crash when rebuilding many jobs in succession

### ISSUE THREAD

**Issue by craigfe** [ocurrent/citty#17]
It is possible to consistently crash `citty` by rebuilding ~5+ jobs on the same ref in quick succession. This is unfortunate, as this is currently the only way of updating the world-view on a PR (after, say, a Docker image upgrade in the background).

An example output:
```bash
ᐅ make run
dune build ./src/main.bc
dune exec ./src/main.bc 2> error.log

make: *** [Makefile:6: run] Error 2
```

**Comment by let-def** [comment]
I just merged the #15 which should fix this issue :).
