### ISSUE TITLE
citty only shows the first build

### ISSUE THREAD

**Issue by talex5** [ocurrent/citty#5]
ocaml-ci tests each PR against multiple base images (at the moment, alpine-3.10-ocaml-4.08 and debian-10-ocaml-4.08, but there will be more soon). citty only shows the first one, so you can't see anything about the Debian builds. Also, you can't tell which build you're looking at.

**Comment by talex5** [comment]
ocaml-ci also provides a summary of why each build failed. This could be displayed with the list of builds. e.g. in the CLI we have:

```
$ ocaml-ci mirage/irmin pull/523
alpine-3.10-ocaml-4.08 (failed: Library "metrics-unix" not found)
debian-10-ocaml-4.08 (failed: Library "metrics-unix" not found)
```

**Comment by craigfe** [comment]
The main issue was fixed by https://github.com/ocaml-ci/citty/pull/8; the summary issue has already been fixed in a separate PR.

I suggest that this issue can now be closed.
